### ISSUE TITLE
Structure of java project

### ISSUE THREAD

**Issue by Ice94** [Ice94/WorldOfWarships#3]
Add folder structure of the java project.

**Comment by Ice94** [comment]
Done.

**Comment by LIttleAncientForestKami** [comment]
Despite "Done" it's still opened. ;-)

**Comment by Ice94** [comment]
Because this is not on holy master, so done, but not approved by reviewers.

**Comment by LIttleAncientForestKami** [comment]
Then sorry, cause I closed others if they had a ready label and I apparently shouldn't.
