### ISSUE TITLE
Rules of writing code!

### ISSUE THREAD

**Issue by Ice94** [Ice94/WorldOfWarships#5]
1. We have to integrate the same live templates. 
2. Each commit should have the formatted code.
3. Default template when creating a new file.
4. @test annotation before each test method.
5. Each feature has the own branch.

**Comment by LIttleAncientForestKami** [comment]
I suggest you to turn this into either markdown file (like readme.md) and make it a part of the repository or to use GitHub Wiki. You also need to describe how to finish feature branches, do you not? Like, when to push, what tests shall be there, when Jenkins, internal and external reviewers come to play...
